Detect and execute OrgBabel tangling

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -28,6 +28,15 @@ export_env_dir() {
 
 export_env_dir $ENV_DIR
 
+# tangle org files
+if [ ! -r $BUILD_DIR/$ORG_BUILD_FILE ]; then
+    echo " !   No ORG_BUILD_FILE found; aborting"
+    exit 1
+fi
+echo "-----> Tangling org files..."
+$BUILD_DIR/org/tangle.sh $BUILD_DIR/$ORG_BUILD_FILE
+echo "       ...done"
+
 # Load common JVM functionality from https://github.com/heroku/heroku-buildpack-jvm-common
 JVM_COMMON_BUILDPACK=${JVM_COMMON_BUILDPACK:-https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/jvm-common.tgz}
 mkdir -p /tmp/jvm-common
@@ -107,4 +116,3 @@ fi
 rm -rf $CACHE_STORE_DIR
 mkdir -p $(dirname $CACHE_STORE_DIR)
 cp -r $CACHE_TARGET_DIR $CACHE_STORE_DIR
-
